name: Generate UML Diagrams

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'Server/SeaBattle/**/*.cs'
      - '.github/workflows/generate-uml.yml'

jobs:
  generate-uml:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Install PlantUML
      run: |
        sudo apt-get update
        sudo apt-get install -y plantuml graphviz

    - name: Install dotnet-uml tool
      run: |
        dotnet tool install --global dotnet-uml

    - name: Generate UML diagrams
      run: |
        mkdir -p docs/diagrams/generated
        
        # Генерация диаграмм для основных компонентов
        for dir in Controllers Models Services Hubs; do
          if [ -d "Server/SeaBattle/$dir" ]; then
            echo "Generating diagram for $dir"
            dotnet uml class Server/SeaBattle/$dir --output docs/diagrams/generated/$dir.puml
            plantuml docs/diagrams/generated/$dir.puml
          fi
        done
        
        # Генерация общей диаграммы проекта
        dotnet uml class Server/SeaBattle --output docs/diagrams/generated/full-project.puml
        plantuml docs/diagrams/generated/full-project.puml

    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/diagrams/generated/
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update UML diagrams" && git push) 